### ISSUE TITLE
Should this gem make network requests upon require?

### ISSUE THREAD

**Issue by mensfeld** [Da2dalus/textgem#1]
ey,

My name is Maciej Mensfeld and I run a research security project called diffend.io.

I've noticed, that this library performs request upon just being required (not used) here: https://my.diffend.io/gems/textgem/0.2.0#d2h-765355-1455

Is that intended? Usually, it's a debug leftover that can cause some systems to crash when artifacts are built without network access and in general is not recommended.

Thanks!

**Comment by Da2dalus** [comment]
This is already fixed in version 0.2.2. The bug was caused by;
```ruby
include Textgem
Textgem.quota("textbely")
```
in /lib/textgem.rb.
I used it to test the module, but I forgot to delete it.
